name: MacOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      # - uses: actions/cache@v1
      #   name: Cache ~/.stack
      #   with:
      #     path: ~/.stack
      #     key: ${{ runner.os }}-stack-${{ github.sha }}
      #     restore-keys: ${{ runner.os }}-stack-

      - name: Install SDL dependency (for SDL tests)
        run: |
          brew install sdl2       \
                       sdl2_gfx   \
                       sdl2_image \
                       sdl2_mixer \
                       sdl2_ttf

      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Build
        run: stack build

      - name: Run Compiler Tests
        run: stack test

      - name: Run Carp Tests
        run: ./scripts/run_carp_tests.sh

